### ISSUE TITLE
Additional info for "Search Hunters"

### ISSUE THREAD

**Issue by JSKoenig** [majikat768/HuntStatsLogger#44]
It would be nice if when searching a hunters name it showed how many times you've killed them and they've killed you. Currently you only see how many matches you've seen them in.
![000271](https://user-images.githubusercontent.com/41165269/210700204-fb58d86b-5651-4976-a568-d4ff01af83cc.png)

**Comment by majikat768** [comment]
It should be able to provide this info, if there is any available....so, if you've only been in a Hunt with them before but not interacted, then it'll just have the one line, "You've seen [hunter] in [n] hunts."  But if you've killed/been killed by them, or been on their team, or if they've had other steam names, it should provide that information as well.

**Comment by JSKoenig** [comment]
I'm running the latest code and it doesn't seem to be working like you're showing

![000274](https://user-images.githubusercontent.com/41165269/211210985-a193c1e5-afdf-43c8-b7e0-59d8ca277dc1.png)
![000274](https://user-images.githubusercontent.com/41165269/211211032-fa9fa6db-1d9e-4db0-b081-6e452a10f920.png)

**Comment by JSKoenig** [comment]
I'm running the latest code and it doesn't seem to be working like you're showing
![000274](https://user-images.githubusercontent.com/41165269/211211223-4a99ffbe-212c-408e-a3ea-fc691fdb478e.png)
![000275](https://user-images.githubusercontent.com/41165269/211211224-12f09805-76c2-4489-9bcd-c9207a389d14.png)

**Comment by majikat768** [comment]
Oh you're right!  I must have not included some changes in the last push.  I'll get that fixed.  Thanks!

**Comment by majikat768** [comment]
Just pushed an update which should fix this.

**Comment by JSKoenig** [comment]
Still having the same issue. I could try wiping my db and see if that make a difference

**Comment by majikat768** [comment]
That's possible, in settings try setting KDA and hunt dropdown timespan to All Time...I think that may affect how it's calculated.

**Comment by JSKoenig** [comment]
Looks like the issue has to do with having old data, works fine now.
